title: World of SteelCraft Service Status
languageCode: en
defaultContentLanguage: en
baseURL: https://status.worldofsteelcraft.tk

params:
  # Before setting up your systems, you need
  # to first define at least one category.
  #
  # Categories are shown in the order that
  # you define in this config file.
  #
  # Categories can have a:
  # - name
  # - description
  # - closed boolean `closed: true`
  #   That would collapse the category upon first load
  #   and the user can expand by clicking on the category
  #   (Requires JavaScript.)
  # - untitled boolean `untitled: true`
  #   This would complerely hide the name of the category.
  #   This is useful, if you do not want to use categories
  #   because you need to set an 'Uncategorized' category.
  #   Or it can be used alongside other categories.
  #
  # These are case sensitive.
  # 
  # For help, see the wiki:
  # https://github.com/cstate/cstate/wiki/Customization
  categories:
    - name: Website
      description: The main servers are located here.
      closed: false
    - name: Minecraft Server
      description: 
      closed: false
    - name: Other Services
      description: The other services of World of SteelCraft.
      closed: false

  # These are your systems. Change them to
  # change the amount of components.
  #
  # These are case sensitive.
  #
  # For help, see the wiki:
  # https://github.com/cstate/cstate/wiki/Customization
  systems:
    - name: Website
      description: The web frontend for the application.
      category: Website
      link: https://worldofsteelcraft.tk
    - name: Website Beta
      description: The web frontend for the application.
      category: Website
      link: https://beta.worldofsteelcraft.tk
    - name: WoSC SMP Server
      description: The SMP Server of WoSC.
      category: Minecraft Server
    - name: WoSC Files
      description: The file server of World of SteelCraft based on Google Drive
      category: Other Services
    - name:	WoSC Link Service 1
      description: This is the service responsible for simple links for just redirecting users.
      category: Other Services
    - name:	WoSC Link Service 2
      description: This is the service responsible for redirecting users to call the special applications to serve the content to users.
      category: Other Services

  dateFormat: January 2, 2006 at 3:04 PM UTC
  shortDateFormat: 15:04 UTC — Jan 2
  useRelativeTime: true
  skipSeconds: false
  enableLastMod: true
  useLargeHeaderDesign: false
  incidentHistoryFormat: "monthly"
  disableIncidentHistory: false
  disableDarkMode: true
  useLogo: true
  logo: https://worldofsteelcraft.tk/images/logo.png

  # This is the description that is shown
  # on the footer and meta tags.
  #
  # Default: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.

  # Disable complex server-side
  # calculations that may impact
  # your build performance
  #
  # Disables math calculations
  # for average downtime on
  # systems ("/affected/") pages
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  disableComplexCalculations: false

  incidentPostsPerPage: 10

  # Colors throughout cState
  #
  # We recommend using HEX
  # (with the # symbol).
  #
  # Defaults:
  #
  # brand: "#0a0c0f"
  # ok: "#008000"
  # disrupted: "#cc4400"
  # down: "#e60000"
  # notice: "#24478f"
  brand: "#32e532"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"

  # If the status page shows that
  # there are disruptions or outages
  # happening, should it keep the
  # brand header color or drop it
  # and use the status indication
  # colors that were just defined?
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  alwaysKeepBrandColor: false

  # Introduced in v4.0.1 for consistent
  # site title text color.
  #
  # If you do not use the logo, what color
  # should the site text color be?
  #
  # Removing this option will not force
  # any site text color. This is likely
  # unwanted behavior.
  #
  # Default: `white`
  # STRING; `white`, `black`, or nothing
  headerTextColor: white

# These options affect the core of cState.
# Please do not change them if you do not
# know what you are doing.
theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml